name: Deploy Unmanaged Solution to Prod

permissions:
  contents: read

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Export Unmanaged Solution from Dev"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SOLUTION_NAME: emp_leave
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install PAC CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      - name: WhoAmI (Prod)
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ secrets.PP_PROD_URL }}
          tenant-id: ${{ secrets.PP_PROD_TENANT_ID }}
          app-id: ${{ secrets.PP_PROD_CLIENT_ID }}
          client-secret: ${{ secrets.PP_PROD_CLIENT_SECRET }}

      - name: Import Unmanaged solution into Prod
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ secrets.PP_PROD_URL }}
          tenant-id: ${{ secrets.PP_PROD_TENANT_ID }}
          app-id: ${{ secrets.PP_PROD_CLIENT_ID }}
          client-secret: ${{ secrets.PP_PROD_CLIENT_SECRET }}
          solution-file: out/${{ env.SOLUTION_NAME }}_Unmanaged.zip
          publish-changes: false
          overwrite-unmanaged-customizations: true

      - name: Publish customizations in Prod
        run: |
          pac auth create --url ${{ secrets.PP_PROD_URL }} --client-id ${{ secrets.PP_PROD_CLIENT_ID }} --client-secret ${{ secrets.PP_PROD_CLIENT_SECRET }} --tenant-id ${{ secrets.PP_PROD_TENANT_ID }} --name ProdAuth
          pac solution publish --environment ProdAuth --name ${{ env.SOLUTION_NAME }}
