name: Dev to Prod (Cross-Tenant) Unmanaged Deployment

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "solutions/**"

jobs:
  dev-to-prod:
    runs-on: ubuntu-latest
    env:
      SOLUTION_NAME: emp_leave

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      # Create a unique filename using timestamp
      - name: Set unique filename
        id: set_filename
        run: echo "file_name=${{ env.SOLUTION_NAME }}_Unmanaged_$(date +'%Y%m%d_%H%M%S').zip" >> $GITHUB_ENV

      # Export solution from Dev
      - name: Export solution from Dev
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ secrets.PP_DEV_URL }}
          tenant-id: ${{ secrets.PP_DEV_TENANT_ID }}
          app-id: ${{ secrets.PP_DEV_CLIENT_ID }}
          client-secret: ${{ secrets.PP_DEV_CLIENT_SECRET }}
          solution-name: ${{ env.SOLUTION_NAME }}
          managed: false
          overwrite: true
          solution-output-file: solutions/${{ env.file_name }}

      # Upload exported file as artifact
      - name: Upload exported solution
        uses: actions/upload-artifact@v4
        with:
          name: exported-solution
          path: solutions/${{ env.file_name }}

  import-to-prod:
    runs-on: ubuntu-latest
    needs: dev-to-prod
    env:
      SOLUTION_NAME: emp_leave

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      # Download exported solution artifact
      - name: Download exported solution
        uses: actions/download-artifact@v4
        with:
          name: exported-solution
          path: solutions/

      # Get filename dynamically from downloaded folder
      - name: Get solution file name
        id: getfile
        run: echo "SOLUTION_FILE=$(ls solutions/*.zip)" >> $GITHUB_ENV

      # Authenticate to Prod Tenant
      - name: WhoAmI (Prod)
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ secrets.PP_PROD_URL }}
          tenant-id: ${{ secrets.PP_TENANT_ID }}
          app-id: ${{ secrets.PP_CLIENT_ID }}
          client-secret: ${{ secrets.PP_CLIENT_SECRET }}

      # Import solution to Prod
      - name: Import solution to Prod
        uses: microsoft/powerplatform-actions/import-solution@v1
        with:
          environment-url: ${{ secrets.PP_PROD_URL }}
          tenant-id: ${{ secrets.PP_TENANT_ID }}
          app-id: ${{ secrets.PP_CLIENT_ID }}
          client-secret: ${{ secrets.PP_CLIENT_SECRET }}
          solution-file: ${{ env.SOLUTION_FILE }}
          publish-changes: false
          overwrite-unmanaged-customizations: true

      # Publish customizations
      - name: Publish customizations
        run: |
          pac auth create --url ${{ secrets.PP_PROD_URL }} --client-id ${{ secrets.PP_CLIENT_ID }} --client-secret ${{ secrets.PP_CLIENT_SECRET }} --tenant-id ${{ secrets.PP_TENANT_ID }} --name ProdAuth
          pac solution publish --environment ProdAuth --name ${{ env.SOLUTION_NAME }}
