name: Export Unmanaged from Dev

permissions:
  contents: write
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - "solutions/**"

jobs:
  export:
    runs-on: ubuntu-latest
    env:
      SOLUTION_NAME: emp_leave
    steps:
      # 1. Checkout repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Install PAC CLI
      - name: Install PAC CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      # 3. WhoAmI (Dev)
      - name: WhoAmI (Dev)
        uses: microsoft/powerplatform-actions/who-am-i@v1
        with:
          environment-url: ${{ secrets.PP_DEV_URL }}
          tenant-id: ${{ secrets.PP_DEV_TENANT_ID }}
          app-id: ${{ secrets.PP_DEV_CLIENT_ID }}
          client-secret: ${{ secrets.PP_DEV_CLIENT_SECRET }}

      # 4. Export Unmanaged Solution
      - name: Export solution (Unmanaged) from Dev
        uses: microsoft/powerplatform-actions/export-solution@v1
        with:
          environment-url: ${{ secrets.PP_DEV_URL }}
          tenant-id: ${{ secrets.PP_DEV_TENANT_ID }}
          app-id: ${{ secrets.PP_DEV_CLIENT_ID }}
          client-secret: ${{ secrets.PP_DEV_CLIENT_SECRET }}
          solution-name: ${{ env.SOLUTION_NAME }}
          managed: false
          overwrite: true
          solution-output-file: out/${{ env.SOLUTION_NAME }}_Unmanaged.zip

      # 5. Upload exported solution as artifact
      - name: Upload solution artifact
        uses: actions/upload-artifact@v3
        with:
          name: solution-zip
          path: out/${{ env.SOLUTION_NAME }}_Unmanaged.zip
